# Generated by Django 4.2.17 on 2025-07-03 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', encrypted_model_fields.fields.EncryptedCharField()),
                ('account_name', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('account_id', encrypted_model_fields.fields.EncryptedTextField(unique=True)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit', 'Credit Card')], max_length=50)),
                ('balance', encrypted_model_fields.fields.EncryptedCharField(default='0.00')),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
