# Generated by Django 4.2.17 on 2025-01-24 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_savingsgoal_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsgoal',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='goal_date',
            field=models.DateField(default=datetime.date(2025, 1, 24)),
            preserve_default=False,
        ),
    ]
