# Generated by Django 4.2.17 on 2025-02-10 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='current_amount',
        ),
        migrations.AlterField(
            model_name='budget',
            name='last_reset_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
