# Generated by Django 4.2.17 on 2025-02-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_customuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
    ]
