# Generated by Django 4.2.17 on 2025-02-26 07:57

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='plaid_access_token',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
