# Generated by Django 4.2.17 on 2025-02-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_id',
            field=models.CharField(unique=True),
        ),
    ]
