# Generated by Django 4.2.17 on 2025-03-02 09:40

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_bankaccount_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='balance',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=encrypted_model_fields.fields.EncryptedTextField(default='GBP'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='is_active',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=True),
        ),
    ]
