# Generated by Django 4.2.17 on 2025-03-02 13:59

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_bankaccount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance_encrypted',
            field=encrypted_model_fields.fields.EncryptedTextField(default=0),
            preserve_default=False,
        ),
    ]
