# Generated by Django 4.2.17 on 2025-03-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_bankaccount_balance_encrypted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='balance_encrypted',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(default='GBP', max_length=10),
        ),
    ]
