# Generated by Django 4.2.17 on 2025-03-03 13:51

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_bankaccount_balance_encrypted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=encrypted_model_fields.fields.EncryptedCharField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
