# Generated by Django 4.2.17 on 2025-03-03 17:28

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_bankaccount_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=encrypted_model_fields.fields.EncryptedCharField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
