# Generated by Django 4.2.17 on 2025-03-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_transaction_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account_id',
        ),
    ]
