# Generated by Django 4.2.17 on 2025-03-05 11:24

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_transaction_amount_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=encrypted_model_fields.fields.EncryptedCharField(default='0.00'),
        ),
    ]
