# Generated by Django 4.2.17 on 2025-03-05 14:28

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_transaction_amount_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.bankaccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
