# Generated by Django 4.2.17 on 2025-03-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_transaction_bank_account_alter_transaction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='plaid_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('user', 'bank_account', 'name', 'amount', 'date'), name='unique_user_transaction'),
        ),
    ]
