# Generated by Django 4.2.17 on 2025-03-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_transaction_plaid_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_user_transaction',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('user', 'bank_account', 'name', 'amount', 'date', 'category'), name='unique_user_transaction'),
        ),
    ]
