# Generated by Django 4.2.17 on 2025-03-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_transaction_unique_user_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_user_transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='plaid_transaction_id',
        ),
    ]
