# Generated by Django 4.2.17 on 2025-03-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_budget_current_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
