# Generated by Django 4.2.17 on 2025-04-17 14:24

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=encrypted_model_fields.fields.EncryptedTextField(unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=encrypted_model_fields.fields.EncryptedTextField(unique=True, verbose_name='Username'),
        ),
    ]
