# Generated by Django 4.2.17 on 2025-04-21 08:15

import app.models.savingsGoal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_savingsgoal_current_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='goal_date',
            field=models.DateField(validators=[app.models.savingsGoal.validate_future_date]),
        ),
    ]
