# Generated by Django 4.2.17 on 2025-07-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
