# Generated by Django 4.2.17 on 2025-07-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_delete_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
